spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://7001.eureka.com:7001/eureka/,http://7002.eureka.com:7002/eureka/,http://7003.eureka.com:7003/eureka/
    instance:
      instance-id: microservicecloud-config-client-dev
      prefer-ip-address: true     # 访问路径可以显示IP地址
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: microservicecloud-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://7001.eureka.com:7001/eureka/,http://7002.eureka.com:7002/eureka/,http://7003.eureka.com:7003/eureka/
    instance:
      instance-id: microservicecloud-config-client-test
      prefer-ip-address: true     # 访问路径可以显示IP地址