server:
  port: 7003

eureka:

  instance:
    hostname: 7003.eureka.com

  client:
    service-url:
      defaultZone: http://7001.eureka.com:7001/eureka,http://7002.eureka.com:7002/eureka
    register-with-eureka: false
    fetch-registry: false
