server:
  port: 7001


# Eureka 服务端配置
eureka:

  instance:
    # hostname: localhost
    hostname: 7001.eureka.com

  client:
    register-with-eureka: false  # false：表示不向注册中心注册自己。
    fetch-registry: false  # false：表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://7002.eureka.com:7002/eureka,http://7003.eureka.com:7003/eureka




